### ISSUE TITLE
Design: bitte Einträge im Block so wie im Kursteilnehmer-Block

### ISSUE THREAD

**Issue by relecand** [sudile/moodle-block_courseadmin#2]
![screenshot 2015-09-23 12 49 24](https://cloud.githubusercontent.com/assets/5286499/10043249/b7b2a452-61f1-11e5-8d1f-a897b6e6afb7.png)

**Comment by relecand** [comment]
also ohne Linie und linksbündig

**Comment by jojoob** [comment]
Habe die CSS Regeln aus dem block_settings übernommen, daher die Darstellung.

**Comment by relecand** [comment]
Ok, super. Klappt jetzt mit CSS Anpassung im Theme. Danke!
